### ISSUE TITLE
validate required fields

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/nfpm#100]
maybe we should add a step to validate that required fields were provided?

I'm not sure about debs, but RPMs seem to like to complain about missing required fields :) 

see https://github.com/goreleaser/goreleaser/issues/1229 for more context

**Comment by erikgeiser** [comment]
We should also print warnings to `stderr` when top level config options are not supported by the package format that is currently being built. If a configuration option is top level and not package specific, users would otherwise expect it to have an effect on all formats. I think `apk` files currently don't support some options.

**Comment by caarlos0** [comment]
this was fixed in #372
