### ISSUE TITLE
Globbing Replacement

### ISSUE THREAD

**Issue by rtpt-erikgeiser** [goreleaser/nfpm#232]
As far as I am aware, it is currently impossible to package files or directories that are enclosed in curly braces (such as `{foo}`). An example would be Firefox extensions which use `{UUID}` directories. The reason for this is that https://github.com/mattn/go-zglob does not seem to support wildcard escaping and because also because of a bug (https://github.com/mattn/go-zglob/issues/32).

A possible alternative to replace https://github.com/mattn/go-zglob with is https://github.com/gobwas/glob which supports the same features, escaping and more extensive tests. However, this library only does string matching and the directory walking will have to be performed in `nfpm`.

**Comment by rtpt-erikgeiser** [comment]
The maintainer of https://github.com/mattn/go-zglob has just added escaping support and the issue should be fixed if the library is upgraded. However, I'm not a fan of `zglob`'s approach of building a regular expression. Maybe we can discuss moving to https://github.com/gobwas/glob at some point @caarlos0, wdyt?

**Comment by caarlos0** [comment]
hmm, interesting... we can test the other lib too, yes... can you open a PR?

**Comment by rtpt-erikgeiser** [comment]
I just tried to upgrade `zglob` but it is still buggy, I created another issue over there. If the maintainer fixes it we should just upgrade first and at some point I will also create a PR with https://github.com/gobwas/glob which we can then try out and compare before merging it.

**Comment by caarlos0** [comment]
awesome, thanks!

**Comment by erikgeiser** [comment]
It's fixed now, at least for my use case. However, I think asterisks still cannot be escaped but I'm not sure.

For a long term solution I still think we should switch to https://github.com/gobwas/glob which uses a proper lexer, parser and compiler instead of building a regular expression. The only issue is that it only does matching, so we'll have to implement file walking ourselves. Another thing I would like to add is a an option to disable globbing altogether (we can just use `glob.QuoteMeta` for this). This option would make `nfpm` far more predictable when using it as part of a bigger build system that auto-populates the `files` field.

What do you think @caarlos0?

**Comment by caarlos0** [comment]
sounds like a plan @erikgeiser

**Comment by nhooyr** [comment]
This seems to have broken recursive globs like the following:

https://github.com/cdr/code-server/blob/1826399cd230acc1f62556a5af7bba9c25a03a25/ci/build/nfpm.yaml#L19

Only directories are copied now whereas before all files were.

Caused a regression in code-server as nfpm wouldn't include the files in `./release-standalone/*` but only `./release-standalone/**/*`.

See https://github.com/cdr/code-server/issues/2310

**Comment by nhooyr** [comment]
For now we've rolled back nfpm to v1.9.0

**Comment by caarlos0** [comment]
addressed @nhooyr's comments in #256
