### ISSUE TITLE
Symlink permissions are dropped

### ISSUE THREAD

**Issue by zwass** [goreleaser/nfpm#286]
It seems that the permissions specified for symlinks are ignored entirely (see https://github.com/goreleaser/nfpm/blob/master/deb/deb.go#L198-L206).

Is there a reason that permissions cannot be set for symlinks?

**Comment by djgilcrease** [comment]
Will take a look at that tomorrow

**Comment by djgilcrease** [comment]
From https://unix.stackexchange.com/questions/87200/change-permissions-for-a-symbolic-link
```On most systems, symlink permissions don't matter. When using the symlink, the permissions of the components of symlink's target will be checked. However, on some systems they do matter. MacOS requires read permission on the link for readlink, and NetBSD's symperm mount option forces link permissions checks on read and traversal. On those systems (and their relatives, including FreeBSD and OpenBSD) there is a equivalent -h option to chmod.```

And in my testing the `Typeflag: tar.TypeSymlink` for apk & deb overrides whatever you set the mode as and always sets `777`. For rpm `Mode:  uint(cpio.S_ISLNK)` does the same thing, even when I tried `Mode:  uint(cpio.S_ISLNK&file.FileInfo.Mode)`

So I think this is by design that you cannot change the permissions on a symlink.

**Comment by zwass** [comment]
Good find. Thank you for digging into that! I hadn't even tried it. Will close this issue and reopen if I notice any issues.
