### ISSUE TITLE
slow rpm/armv7 tests

### ISSUE THREAD

**Issue by caarlos0** [goreleaser/nfpm#555]
the `build / acceptance-tests (rpm, armv7)` test run takes ages to run, sometimes timing out... seems to be related to slow rpm servers for arm7... 

I wonder if its worth keeping this in the build... I never wait for it anyway 🤔 

wdyt? @goreleaser/nfpm

**Comment by erikgeiser** [comment]
We could publish a base image where all the tools we need are already installed, if the issue is caused by the dnf/rpm package repositories.

**Comment by caarlos0** [comment]
> We could publish a base image where all the tools we need are already installed, if the issue is caused by the dnf/rpm package repositories.

I **think** I tried that a while ago, if I recall correctly, even `yum update` was taking several minutes... 

Maybe I did something wrong though, not used to rpm-based distros... wanna give it a try?

**Comment by erikgeiser** [comment]
Ah I see, we cannot pre-install everything because a part of our tests is to test pulling in package as dependencies. [This](https://access.redhat.com/solutions/1355683) looks like we can create a local repository in the filesystem. Then a solution would look like this:

* Run `yum update`
* Install all the tools we need
* Setup a local repository with dummy packages we can use in tests
* Remove all other repositories
* Use the result as the base image

**Comment by caarlos0** [comment]
hmm, sounds like a good plan
