### ISSUE TITLE
ppc64le support

### ISSUE THREAD

**Issue by sumitd2** [goreleaser/nfpm#728]
### Is your feature request related to a problem? Please describe.

ppc64le artifacts are currently not being published to the releases page.

### Describe the solution you'd like

We would like to open a PR for ppc64le support.

### Describe alternatives you've considered

ppc64le seems to be there already in some source files.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Hi team,

I am from the IBM Power (ppc64le) porting team. We would like to open a PR for ppc64le support so that the artifacts are published to the releases page for subsequent releases. I searched through the source files but could not find where to make this change. Can you please help?

Thank you.

**Comment by gerrith3** [comment]
@caarlos0 I'm not sure I understand your comment about "ppc64le getting more popular"?  You do realize that most of the world's mid-tier banking systems are built on IBM's Power, as well as major modern retailers use ppc64le daily?  Your credit card/debit card and banking transactions most likely all run through Linux on Power and even specifically some of the code for which your project is a dependency?  And that's just one or two areas where it is heavily used.  I would love to ask you to reconsider because your reasoning seems to be based on a lack of info, as opposed to a technical reason?

**Comment by caarlos0** [comment]
sorry, I meant as a CI and/or dev machine...

I'm aware its widely used as servers, but I've never heard of anyone using it as a main machine to work on stuff, or as a CI.

nfpm is a dev tool, you can still package to ppc64 with it, I just don't know why you would do that FROM a ppc64...

**Comment by gerrith3** [comment]
We do *everything* FROM ppc64le.  ;)  Most of the major banks and customers that use Power have a line drawn between x86-64 server management and ppc64le server management and we are similar for development in that everything we build and ship tends to be build on ppc64le.  Why would we need any Intel servers for anything?  :)

**Comment by caarlos0** [comment]
yes, since you work at ibm on the powerpc team, I would assume you use it all the time... 

I think the right question is: is this a real use case (do you actually need/want to use nfpm on powerpc), or is it just part of an effort to package everything to ppc?

**Comment by gerrith3** [comment]
We actually use nfpm on pppc64le.
